<?php
// $Id: masschallenge.install

/**
 * Implementation of hook_install()
 */
function mc_judgedash_install() {
  // Set the module weight so it can override other modules.
  db_query("UPDATE {system} SET weight = 99 WHERE name = 'mc_judgedash'");
}

/**
 * Implementation of hook_uninstall()
 */
function mc_judgedash_uninstall() {
  // Remove the module from the system table
  db_query("DELETE FROM {system} WHERE name = 'mc_judgedash'");
}
